name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'  # Trigger on version tags like v1.0.1, v2.1.0, etc.

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build AppImage using Docker
        run: make dist-linux

      - name: Get version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*.AppImage
          name: Release ${{ github.ref_name }}
          body: |
            ## Changes in this release

            See the [commit history](https://github.com/${{ github.repository }}/commits/${{ github.ref_name }}) for details.

            ## Download

            Download the AppImage below and make it executable:
            ```bash
            chmod +x AIDeskWrap-${{ steps.get_version.outputs.VERSION }}.AppImage
            ./AIDeskWrap-${{ steps.get_version.outputs.VERSION }}.AppImage
            ```
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
